on:
  push:
    branches : [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run testing
        env:
          TF_ACC: true
          APPCLACKS_API_ENDPOINT: "https://api.appclacks.com"
          APPCLACKS_USERNAME: ${{ secrets.APPCLACKS_USERNAME }}
          APPCLACKS_PASSWORD: ${{ secrets.APPCLACKS_PASSWORD }}
        run: go test -race -v ./...
